POST https://tame-hummingbird-105.convex.site/createInitialSysAdmin
content-type: application/json

{
  "email": "gideonshujaa@gmail.com",
  "name": "Shujaa",
  "token": "your_very_secret_token_here"
}