/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as emails_Organisationinvitation from "../emails/Organisationinvitation.js";
import type * as emails_OrgsUserInvitation from "../emails/OrgsUserInvitation.js";
import type * as emails_VerificationCodeEmail from "../emails/VerificationCodeEmail.js";
import type * as helper_helper from "../helper/helper.js";
import type * as helper_index from "../helper/index.js";
import type * as helper_sendMail from "../helper/sendMail.js";
import type * as http from "../http.js";
import type * as Organisation_organisationInvitation from "../Organisation/organisationInvitation.js";
import type * as Organisation_organisations from "../Organisation/organisations.js";
import type * as Organisation_OrganisationToUser from "../Organisation/OrganisationToUser.js";
import type * as Organisation_sendOrganisationInvitation from "../Organisation/sendOrganisationInvitation.js";
import type * as OTP_ResendOTP from "../OTP/ResendOTP.js";
import type * as payment_payment_db from "../payment/payment_db.js";
import type * as payment_paystack from "../payment/paystack.js";
import type * as schemas_auth from "../schemas/auth.js";
import type * as schemas_organisation from "../schemas/organisation.js";
import type * as schemas_payments from "../schemas/payments.js";
import type * as schemas_sysAdmin from "../schemas/sysAdmin.js";
import type * as systemAdmin_sysAdmin from "../systemAdmin/sysAdmin.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  "emails/Organisationinvitation": typeof emails_Organisationinvitation;
  "emails/OrgsUserInvitation": typeof emails_OrgsUserInvitation;
  "emails/VerificationCodeEmail": typeof emails_VerificationCodeEmail;
  "helper/helper": typeof helper_helper;
  "helper/index": typeof helper_index;
  "helper/sendMail": typeof helper_sendMail;
  http: typeof http;
  "Organisation/organisationInvitation": typeof Organisation_organisationInvitation;
  "Organisation/organisations": typeof Organisation_organisations;
  "Organisation/OrganisationToUser": typeof Organisation_OrganisationToUser;
  "Organisation/sendOrganisationInvitation": typeof Organisation_sendOrganisationInvitation;
  "OTP/ResendOTP": typeof OTP_ResendOTP;
  "payment/payment_db": typeof payment_payment_db;
  "payment/paystack": typeof payment_paystack;
  "schemas/auth": typeof schemas_auth;
  "schemas/organisation": typeof schemas_organisation;
  "schemas/payments": typeof schemas_payments;
  "schemas/sysAdmin": typeof schemas_sysAdmin;
  "systemAdmin/sysAdmin": typeof systemAdmin_sysAdmin;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
