import "./globals.css";
import type { Metadata } from "next";
import { chakra, fontSans, protest, roboto, rowdies } from "@/lib/fonts";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ConvexClientProvider } from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            roboto.variable,
            fontSans.variable,
            rowdies.variable,
            protest.variable,
            chakra.variable,
            "font-roboto"
          )}
        >
          <ConvexClientProvider>
            <>
              {children}
              <Toaster />
            </>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
